# Generated by Django 3.0.7 on 2020-07-31 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='usersSign', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
