# Generated by Django 3.0.7 on 2020-07-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200730_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='image',
            field=models.ImageField(upload_to='usersSign', verbose_name='Image'),
        ),
    ]
