# Generated by Django 3.0.7 on 2020-08-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200730_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='updated',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='academicPerformance',
            field=models.CharField(max_length=200, null=True, verbose_name='Desempeño académico (si aplica)'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='accessToInternetAndDevices_Doctor',
            field=models.CharField(max_length=200, null=True, verbose_name='Acceso a internet y dispositivos (doctores)'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='accessToInternetAndDevices_Student',
            field=models.CharField(max_length=200, null=True, verbose_name='Acceso a internet y dispositivos (estudiantes)'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='age',
            field=models.SmallIntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='civilStatus',
            field=models.CharField(max_length=100, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='difficultiesToStudy',
            field=models.CharField(max_length=200, null=True, verbose_name='Dificultades para estudiar'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='factultyYear',
            field=models.CharField(max_length=4, null=True, verbose_name='Año de ingreso a la facultad'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='kids',
            field=models.CharField(max_length=50, null=True, verbose_name='Niños'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='municipality',
            field=models.CharField(max_length=200, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='occupation',
            field=models.CharField(max_length=200, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='semester',
            field=models.CharField(max_length=200, null=True, verbose_name='Semestre (si aplica)'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='seriousWorkProblems',
            field=models.CharField(max_length=200, null=True, verbose_name='Problemas graves en el trabajo'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='sex',
            field=models.CharField(max_length=50, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='typeOfActivity',
            field=models.CharField(max_length=200, null=True, verbose_name='Actividad que realiza'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='typeOfMask',
            field=models.CharField(max_length=200, null=True, verbose_name='Tipo de cubrebocas'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='typeOfResidence',
            field=models.CharField(max_length=200, null=True, verbose_name='Tipo de residencia'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='useOfMask',
            field=models.CharField(max_length=200, null=True, verbose_name='Uso de cubrebocas'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='workDifficulties',
            field=models.CharField(max_length=200, null=True, verbose_name='Dificultades en el trabajo'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='worked',
            field=models.CharField(max_length=50, null=True, verbose_name='Trabajó mientras estudió'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='image',
            field=models.ImageField(unique=True, upload_to='usersSign', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Nombre'),
        ),
    ]
