# Generated by Django 3.0.7 on 2020-08-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200803_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='surveyId',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='ID de registro'),
        ),
    ]
