# Generated by Django 3.0.7 on 2020-08-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usersurvey_surveyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersurvey',
            old_name='factultyYear',
            new_name='facultyYear',
        ),
    ]
